## Analisando dados com Python - I

In [1]:
print("Hello World!")

Hello World!

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

#obs: Aqui no VSCode, para ler excel é necessario instalar o pacote "openpyxl"

In [8]:
df_dengue = pd.read_excel("Base de Dados Dengue.xlsx")

In [9]:
df_dengue.head()

               municipio  uf data_infeccoes  qtd_infeccoes
0  ALTA FLORESTA D'OESTE  RO     2013-01-01             34
1  ALTA FLORESTA D'OESTE  RO     2013-02-01             44
2  ALTA FLORESTA D'OESTE  RO     2013-03-01             15
3  ALTA FLORESTA D'OESTE  RO     2013-04-01              4
4  ALTA FLORESTA D'OESTE  RO     2013-05-01              3

In [10]:
df_dengue.head(20)

                municipio  uf data_infeccoes  qtd_infeccoes
0   ALTA FLORESTA D'OESTE  RO     2013-01-01             34
1   ALTA FLORESTA D'OESTE  RO     2013-02-01             44
2   ALTA FLORESTA D'OESTE  RO     2013-03-01             15
3   ALTA FLORESTA D'OESTE  RO     2013-04-01              4
4   ALTA FLORESTA D'OESTE  RO     2013-05-01              3
5   ALTA FLORESTA D'OESTE  RO     2013-06-01              0
6   ALTA FLORESTA D'OESTE  RO     2013-07-01              0
7   ALTA FLORESTA D'OESTE  RO     2013-08-01              3
8   ALTA FLORESTA D'OESTE  RO     2013-09-01              0
9   ALTA FLORESTA D'OESTE  RO     2013-10-01              0
10  ALTA FLORESTA D'OESTE  RO     2013-11-01              0
11  ALTA FLORESTA D'OESTE  RO     2013-12-01              0
12  ALTA FLORESTA D'OESTE  RO     2014-01-01              0
13  ALTA FLORESTA D'OESTE  RO     2014-02-01              1
14  ALTA FLORESTA D'OESTE  RO     2014-03-01              0
15  ALTA FLORESTA D'OESTE  RO     2014-04-01              0
16  ALTA FLORESTA D'OESTE  RO     2014-05-01              1
17  ALTA FLORESTA D'OESTE  RO     2014-06-01              0
18  ALTA FLORESTA D'OESTE  RO     2014-07-01              0
19  ALTA FLORESTA D'OESTE  RO     2014-08-01              0

In [11]:
df_dengue.tail()

       municipio  uf data_infeccoes  qtd_infeccoes
728767  BRASILIA  DF     2023-08-01            939
728768  BRASILIA  DF     2023-09-01            843
728769  BRASILIA  DF     2023-10-01            686
728770  BRASILIA  DF     2023-11-01           1300
728771  BRASILIA  DF     2023-12-01           5603

In [12]:
df_dengue.tail(20)

       municipio  uf data_infeccoes  qtd_infeccoes
728752  BRASILIA  DF     2022-05-01           7395
728753  BRASILIA  DF     2022-06-01           4139
728754  BRASILIA  DF     2022-07-01           1818
728755  BRASILIA  DF     2022-08-01           1276
728756  BRASILIA  DF     2022-09-01           1385
728757  BRASILIA  DF     2022-10-01           1404
728758  BRASILIA  DF     2022-11-01           1194
728759  BRASILIA  DF     2022-12-01           2039
728760  BRASILIA  DF     2023-01-01           2084
728761  BRASILIA  DF     2023-02-01           2293
728762  BRASILIA  DF     2023-03-01           2738
728763  BRASILIA  DF     2023-04-01           2524
728764  BRASILIA  DF     2023-05-01           2276
728765  BRASILIA  DF     2023-06-01           1522
728766  BRASILIA  DF     2023-07-01            902
728767  BRASILIA  DF     2023-08-01            939
728768  BRASILIA  DF     2023-09-01            843
728769  BRASILIA  DF     2023-10-01            686
728770  BRASILIA  DF     2023-11-01           1300
728771  BRASILIA  DF     2023-12-01           5603